// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: lock_manager.proto

package issuelock

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LockManager_GetStatus_FullMethodName = "/LockManager/GetStatus"
)

// LockManagerClient is the client API for LockManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LockManagerClient interface {
	GetStatus(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockResponse, error)
}

type lockManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewLockManagerClient(cc grpc.ClientConnInterface) LockManagerClient {
	return &lockManagerClient{cc}
}

func (c *lockManagerClient) GetStatus(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockResponse)
	err := c.cc.Invoke(ctx, LockManager_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LockManagerServer is the server API for LockManager service.
// All implementations must embed UnimplementedLockManagerServer
// for forward compatibility.
type LockManagerServer interface {
	GetStatus(context.Context, *LockRequest) (*LockResponse, error)
	mustEmbedUnimplementedLockManagerServer()
}

// UnimplementedLockManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLockManagerServer struct{}

func (UnimplementedLockManagerServer) GetStatus(context.Context, *LockRequest) (*LockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedLockManagerServer) mustEmbedUnimplementedLockManagerServer() {}
func (UnimplementedLockManagerServer) testEmbeddedByValue()                     {}

// UnsafeLockManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LockManagerServer will
// result in compilation errors.
type UnsafeLockManagerServer interface {
	mustEmbedUnimplementedLockManagerServer()
}

func RegisterLockManagerServer(s grpc.ServiceRegistrar, srv LockManagerServer) {
	// If the following call pancis, it indicates UnimplementedLockManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LockManager_ServiceDesc, srv)
}

func _LockManager_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockManagerServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockManager_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockManagerServer).GetStatus(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LockManager_ServiceDesc is the grpc.ServiceDesc for LockManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LockManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "LockManager",
	HandlerType: (*LockManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _LockManager_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lock_manager.proto",
}
